# Generated by Django 3.2.5 on 2021-07-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField()),
                ('type', models.CharField(choices=[('DEPOT', 'depot'), ('RETRAIT', 'retrait'), ('VENTE', 'vente'), ('ACHAT', 'achat'), ('SWAP', 'swap')], max_length=100)),
                ('state', models.CharField(choices=[('EN_COURS', 'en_cours'), ('EXECUTER', 'executer'), ('ANNULER', 'annuler')], default='en_cours', max_length=100)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
