# Generated by Django 3.2.5 on 2021-07-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='africell_money',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='airtel_money',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='ecobank',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='equity_bcdc',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='mpesa',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='orange_money',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='uba',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numero',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('solde', models.FloatField()),
                ('owner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='api.profile')),
            ],
        ),
    ]
