# Generated by Django 3.2.5 on 2021-07-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210709_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='montant',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('name', 'owner_profile')},
        ),
    ]
