# Generated by Django 3.2.5 on 2021-07-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210710_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_currency',
            field=models.CharField(default='BTC', max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_currency',
            field=models.CharField(default='USDT', max_length=15),
        ),
    ]
