# Generated by Django 3.2.6 on 2021-08-25 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(default='USD', max_length=50),
        ),
        migrations.AlterField(
            model_name='currency',
            name='solde',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('name', 'owner')},
        ),
        migrations.RemoveField(
            model_name='currency',
            name='owner_profile',
        ),
    ]
